Repository Ajiet-DevNation/DevNation-CMS, pull requests merged in 2024-10, with the labels that each got.

#20 fixes many typos and links
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 Upgrade Navagtion items
  app/Filament/Resources/UserResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: hacktoberfest, hacktoberfest-accepted

#28 implement navigation groups
  app/Filament/Resources/BranchResource.php
  app/Filament/Resources/CollegeResource.php
  app/Filament/Resources/RoleResource.php
  app/Filament/Resources/UserResource.php
Labels: hacktoberfest, hacktoberfest-accepted

#30 template html integrated
  app/Filament/Resources/EventRegisteraionResource.php
  app/Filament/Resources/EventRegisteraionResource/Pages/CreateEventRegisteraion.php
  app/Filament/Resources/EventRegisteraionResource/Pages/EditEventRegisteraion.php
  app/Filament/Resources/EventRegisteraionResource/Pages/ListEventRegisteraions.php
  app/Filament/Resources/UserResource.php
  app/Models/EventRegisteraion.php
  database/migrations/2024_09_29_170519_create_event_registeraions_table.php
  resources/views/home.blade.php
  routes/web.php
  vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#38 template functionality
  public/assets/css/style.css
  public/assets/js/plugins.js
  public/assets/js/theme.js
  resources/views/home.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#40 contact page integrated and icon fixed
  public/assets/css/style.css
  resources/views/home.blade.php
  resources/views/pages/contact.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#41 Added Event page
  public/assets/css/events.css
  resources/views/pages/events.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#43 implement: Event resource page design
  app/Filament/Resources/EventRegisteraionResource.php
  app/Filament/Resources/EventsResource.php
  app/Filament/Resources/EventsResource/Pages/CreateEvents.php
  app/Filament/Resources/EventsResource/Pages/EditEvents.php
  app/Filament/Resources/EventsResource/Pages/ListEvents.php
Labels: hacktoberfest, hacktoberfest-accepted

#44 added relationship manager to user
  app/Filament/Resources/EventsResource.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/RelationManagers/EventRegistrationsRelationManager.php
Labels: hacktoberfest, hacktoberfest-accepted

#46 The addition of the contribution.md file
  README.md
  contribution.md
Labels: hacktoberfest, hacktoberfest-accepted

#48 Enhance Setup Guide for DevNation-CMS
  README.md
  Setup.md
Labels: hacktoberfest, hacktoberfest-accepted

#49 fix: create new event in wizard
  app/Filament/Resources/EventsResource.php
  app/Filament/Resources/EventsResource/Pages/CreateEvents.php
Labels: hacktoberfest, hacktoberfest-accepted

#51 Dev
  composer.lock
  public/assets/img/logo-dark.png
  public/assets/img/logo.png
  resources/views/home.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#55 Used components and integrated the new design
  public/assets/css/events.css
  public/assets/css/style.css
  resources/views/components/layout.blade.php
  resources/views/components/nav.blade.php
  resources/views/home.blade.php
  resources/views/pages/contact.blade.php
  resources/views/pages/events.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#58 Added events seeder and dynamic events for the frontend
  app/Http/Controllers/EventController.php
  database/seeders/DatabaseSeeder.php
  resources/views/pages/events.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#60 Contact page updated and profile page is added
  public/assets/css/profile.css
  public/assets/css/style.css
  resources/views/components/layout.blade.php
  resources/views/pages/contact.blade.php
  resources/views/pages/profile.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#59 Enhancements to Common Errors and Troubleshooting Section
  Setup.md
  composer.lock
Labels: hacktoberfest, hacktoberfest-accepted

#65 events feature
  app/Http/Controllers/EventController.php
  database/seeders/DatabaseSeeder.php
  public/assets/css/event-details.css
  resources/views/components/layout.blade.php
  resources/views/components/nav.blade.php
  resources/views/pages/event-details.blade.php
  resources/views/pages/events.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#67 Dev
  composer.json
  composer.lock
  storage/debugbar/.gitignore
Labels: hacktoberfest, hacktoberfest-accepted

#69 fea:added gallery model and resource
  app/Filament/Resources/GalleryResource.php
  app/Filament/Resources/GalleryResource/Pages/CreateGallery.php
  app/Filament/Resources/GalleryResource/Pages/EditGallery.php
  app/Filament/Resources/GalleryResource/Pages/ListGalleries.php
  app/Models/gallery.php
  database/factories/GalleryFactory.php
  database/migrations/2024_10_05_032806_create_galleries_table.php
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#70 fea:gallery resource
  app/Filament/Resources/GalleryResource.php
  app/Models/gallery.php
  database/migrations/2024_10_05_032806_create_galleries_table.php
Labels: hacktoberfest, hacktoberfest-accepted

#72 Dev
  app/Filament/Resources/DeveloperGroupResource.php
  app/Filament/Resources/DeveloperGroupResource/Pages/CreateDeveloperGroup.php
  app/Filament/Resources/DeveloperGroupResource/Pages/EditDeveloperGroup.php
  app/Filament/Resources/DeveloperGroupResource/Pages/ListDeveloperGroups.php
  app/Filament/Resources/GalleryResource.php
  app/Filament/Resources/GalleryResource/Pages/CreateGallery.php
  app/Models/DeveloperGroup.php
  app/Providers/Filament/AdminPanelProvider.php
  database/factories/DeveloperGroupFactory.php
  database/migrations/2024_10_05_065012_create_developer_groups_table.php
Labels: hacktoberfest, hacktoberfest-accepted

#73 updated DeveloperGroup resource
  app/Filament/Resources/DeveloperGroupResource.php
  app/Models/DeveloperGroup.php
  database/migrations/2024_10_05_065012_create_developer_groups_table.php
Labels: hacktoberfest, hacktoberfest-accepted

#77 dev
  contributing.md
Labels: hacktoberfest, hacktoberfest-accepted

#79 events page and event details page updated
  app/Http/Controllers/EventController.php
  database/seeders/DatabaseSeeder.php
  public/assets/css/event-details.css
  public/assets/css/events.css
  resources/views/components/layout.blade.php
  resources/views/pages/event-details.blade.php
  resources/views/pages/events.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#80 updated composer
  composer.lock
Labels: hacktoberfest, hacktoberfest-accepted

#81 Add About Page Draft 1
  resources/views/components/layout.blade.php
  resources/views/components/nav.blade.php
  resources/views/pages/about.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#82 feature updates
  app/Http/Controllers/EventController.php
  composer.lock
  database/seeders/DatabaseSeeder.php
  public/assets/css/event-details.css
  public/assets/css/events.css
  resources/views/components/layout.blade.php
  resources/views/components/nav.blade.php
  resources/views/pages/about.blade.php
  resources/views/pages/event-details.blade.php
  resources/views/pages/events.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#83 Dev
  app/Filament/Resources/AmbassadorsResource.php
  app/Filament/Resources/DeveloperGroupResource.php
  app/Filament/Resources/UserResource.php
Labels: hacktoberfest, hacktoberfest-accepted

#90 Added gallery
  app/Http/Controllers/HomeController.php
  app/Models/gallery.php
  public/assets/css/gallery.css
  resources/views/events/show.blade.php
  resources/views/gallery/index.blade.php
  resources/views/gallery/show.blade.php
  resources/views/layouts/app.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#88 Add CODE_OF_CONDUCT.md and SECURITY.md Files for Community Guidelines and Security Policy
  CODE_OF_CONDUCT.md.md
  SECURITY.md
  composer.lock
Labels: hacktoberfest, hacktoberfest-accepted

#91 updated homepage
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#92 updated footer and social links
  resources/views/home/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/inlcudes/footer.blade.php
  resources/views/layouts/inlcudes/nav.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#93 feature dev
  CODE_OF_CONDUCT.md.md
  SECURITY.md
  app/Http/Controllers/HomeController.php
  app/Models/gallery.php
  composer.lock
  public/assets/css/gallery.css
  resources/views/events/show.blade.php
  resources/views/gallery/index.blade.php
  resources/views/gallery/show.blade.php
  resources/views/home/index.blade.php
  resources/views/layouts/app.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#94 Dev
  resources/views/gallery/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#96 added content for home page
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#97 Dhanya212 main
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#95 Enhance DevNation-CMS Homepage with Events Carousel and Updated About Section
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#101 fix:home issue
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#103 Dev
  app/Http/Controllers/HomeController.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#106 Enhanced Styling for Markdown Files Across Multiple Issues
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md.md
  SECURITY.md
  Setup.md
  contributing.md
Labels: hacktoberfest, hacktoberfest-accepted

#109 fea
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md.md
  SECURITY.md
  Setup.md
  contributing.md
  public/assets/draft/about.draft.png
  public/images/quote.png
  resources/views/about/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#110 Enhance Core Members Section and Fix Media View Styling for Quote Block
  public/assets/css/style.css
  resources/views/about/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#112 profile page updated
  public/assets/css/profile.css
  public/assets/js/profile.js
  resources/views/layouts/app.blade.php
  resources/views/profile/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#107 Add Meta Tags and Title for 5 pages
  resources/views/about/index.blade.php
  resources/views/contact/index.blade.php
  resources/views/events/index.blade.php
  resources/views/gallery/index.blade.php
  resources/views/profile/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#113 feature merge
  public/assets/css/profile.css
  public/assets/css/style.css
  public/assets/js/profile.js
  resources/views/about/index.blade.php
  resources/views/contact/index.blade.php
  resources/views/events/index.blade.php
  resources/views/gallery/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/profile/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#114 optimised about section
  resources/views/about/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#115 Images upload for the draft + SEO
  public/harshitha/home page/about us page/about us page (1).jpg
  public/harshitha/home page/about us page/about us small.jpg
  public/harshitha/home page/about us page/join us (1).jpg
  public/harshitha/home page/events/past events1 (1).jpg
  public/harshitha/home page/events/past events2 (1).jpg
  public/harshitha/home page/events/pastevents3 (1).jpg
  public/harshitha/home page/homepage/our community.jpg
  public/harshitha/home page/homepage/why join (1).jpg
  resources/views/about/index.blade.php
  resources/views/contact/index.blade.php
  resources/views/events/index.blade.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#116 feature merge
  public/harshitha/home page/about us page/about us page (1).jpg
  public/harshitha/home page/about us page/about us small.jpg
  public/harshitha/home page/about us page/join us (1).jpg
  public/harshitha/home page/events/past events1 (1).jpg
  public/harshitha/home page/events/past events2 (1).jpg
  public/harshitha/home page/events/pastevents3 (1).jpg
  public/harshitha/home page/homepage/our community.jpg
  public/harshitha/home page/homepage/why join (1).jpg
  resources/views/about/index.blade.php
  resources/views/contact/index.blade.php
  resources/views/events/index.blade.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#117 SEO data changes + draft images upload
  public/draft/12 - Copy.jpg
  public/draft/15.jpg
  public/draft/16 (1).jpg
  public/draft/16.jpg
  public/draft/CSE-COMPUTING-LAB-4-2.jpg
  public/draft/CSE-COMPUTING-LAB-4-4.jpg
  public/draft/CSE-COMPUTING-LAB-6-2.jpg
  public/draft/CSE-COMPUTING-LAB-6.jpg
  public/draft/GD-Room.jpg
  public/draft/central-computer-center.jpg
  public/draft/devnation_event.jpg
  public/draft/home_community.jpg
  public/draft/home_hack.jpg
  public/draft/mca-right.jpg
  public/draft/tec.jpg
  public/draft/workshop.jpg
  resources/views/about/index.blade.php
  resources/views/contact/index.blade.php
  resources/views/events/index.blade.php
  resources/views/events/show.blade.php
  resources/views/gallery/index.blade.php
  resources/views/gallery/show.blade.php
  resources/views/home/index.blade.php
  resources/views/profile/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#119 fea
  public/assets/css/profile.css
  public/draft/12 - Copy.jpg
  public/draft/15.jpg
  public/draft/16 (1).jpg
  public/draft/16.jpg
  public/draft/CSE-COMPUTING-LAB-4-2.jpg
  public/draft/CSE-COMPUTING-LAB-4-4.jpg
  public/draft/CSE-COMPUTING-LAB-6-2.jpg
  public/draft/CSE-COMPUTING-LAB-6.jpg
  public/draft/GD-Room.jpg
  public/draft/central-computer-center.jpg
  public/draft/devnation_event.jpg
  public/draft/home_community.jpg
  public/draft/home_hack.jpg
  public/draft/mca-right.jpg
  public/draft/tec.jpg
  public/draft/workshop.jpg
  resources/views/about/index.blade.php
  resources/views/contact/index.blade.php
  resources/views/events/index.blade.php
  resources/views/events/show.blade.php
  resources/views/gallery/index.blade.php
  resources/views/gallery/show.blade.php
  resources/views/home/index.blade.php
  resources/views/profile/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#122 profile page feature
  public/assets/css/profile.css
  public/devimages/about/about1.jpg
  public/devimages/about/about2.jpg
  public/devimages/about/about3.jpg
  public/devimages/about/about4.jpg
  public/devimages/about/about5.jpg
  public/devimages/about/about6.jpg
  public/devimages/about/about7.jpg
  public/devimages/about/about8.jpg
  public/devimages/events/event10.jpg
  public/devimages/events/event4.jpg
  public/devimages/events/event5.jpg
  public/devimages/events/event6.jpg
  public/devimages/events/event7.jpg
  public/devimages/events/event8.jpg
  public/devimages/events/event9.jpg
  public/devimages/events/events1.jpg
  public/devimages/events/events2.jpg
  public/devimages/events/events3.jpg
  public/devimages/homepage/homepage1.jpg
  public/devimages/homepage/homepage2.jpg
  public/draft/GD-Room.jpg
  public/draft/devnation_event.jpg
  public/draft/home_community.jpg
  public/draft/mca-right.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#123 Dev
  resources/views/contact/index.blade.php
  resources/views/layouts/inlcudes/nav.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#126 event
  public/assets/css/events.css
Labels: hacktoberfest-accepted

#127 Dev
  app/Filament/Resources/GalleryResource.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/RelationManagers/AmbassadorRelationManager.php
  app/Models/CertificateTemplate.php
  app/Models/User.php
  database/factories/CertificateTemplateFactory.php
  database/factories/EventsFactory.php
  database/migrations/2024_10_08_021913_create_certificate_templates_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/team/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#129 fix: user notification
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Models/User.php
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#130 updated list events design
  app/Filament/Resources/EventsResource.php
Labels: hacktoberfest, hacktoberfest-accepted

#134 Dev
  app/Http/Controllers/HomeController.php
  composer.lock
Labels: hacktoberfest, hacktoberfest-accepted

#138 chart widget added
  app/Filament/Widgets/EventRegistrartion.php
  app/Filament/Widgets/UserGrowthPerCurrentMonth.php
  app/Filament/Widgets/UserGrowthPerYear.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: hacktoberfest, hacktoberfest-accepted

#139 chart mereg
  app/Filament/Widgets/EventRegistrartion.php
  app/Filament/Widgets/UserGrowthPerCurrentMonth.php
  app/Filament/Widgets/UserGrowthPerYear.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: hacktoberfest, hacktoberfest-accepted

#142 updated database seeders
  database/factories/UserFactory.php
  database/seeders/DatabaseSeeder.php
Labels: hacktoberfest, hacktoberfest-accepted

#147 added social accounts model
  app/Models/SocialAccounts.php
  database/factories/SocialAccountsFactory.php
  database/migrations/2024_10_12_004059_create_social_accounts_table.php
  database/seeders/DatabaseSeeder.php
Labels: hacktoberfest, hacktoberfest-accepted

#148 added resource
  app/Filament/Resources/SocialAccountsResource.php
  app/Filament/Resources/SocialAccountsResource/Pages/CreateSocialAccounts.php
  app/Filament/Resources/SocialAccountsResource/Pages/EditSocialAccounts.php
  app/Filament/Resources/SocialAccountsResource/Pages/ListSocialAccounts.php
Labels: hacktoberfest, hacktoberfest-accepted

#150 fea: social acc resource
  app/Filament/Resources/SocialAccountsResource.php
Labels: hacktoberfest, hacktoberfest-accepted

#151 Dev
  app/Filament/Resources/SocialAccountsResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: hacktoberfest, hacktoberfest-accepted

#152 update: composer
  composer.lock
Labels: hacktoberfest, hacktoberfest-accepted

#153 Dev
  app/Filament/Resources/SocialAccountsResource.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/RelationManagers/SocialAccountsRelationManager.php
  app/Models/User.php
Labels: hacktoberfest, hacktoberfest-accepted, Upgrade

#155 fix: no events page
  resources/views/events/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#156 Dev
  app/Filament/Resources/SocialAccountsResource.php
  app/Filament/Resources/UserResource/RelationManagers/SocialAccountsRelationManager.php
  resources/views/events/show.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#157 stats-integrated
  app/Filament/Widgets/AStatsOverview.php
  app/Filament/Widgets/AdeveloperGroupsStats.php
Labels: hacktoberfest, hacktoberfest-accepted

#159 fea: added new controller TeamCOntroller
  app/Filament/Resources/UserResource/RelationManagers/EventRegistrationsRelationManager.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/TeamController.php
  resources/views/team/index.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#160 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#161 feature merge
  README.md
  app/Filament/Widgets/AStatsOverview.php
  app/Filament/Widgets/AdeveloperGroupsStats.php
Labels: hacktoberfest, hacktoberfest-accepted

#163 updated team page
  app/Http/Controllers/TeamController.php
  app/Models/Role.php
  composer.lock
  resources/views/team/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#167 feautre merge
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/TeamController.php
  app/Models/Role.php
  composer.lock
  public/assets/css/login.css
  public/assets/css/signup.css
  resources/views/home/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/login/index.blade.php
  resources/views/signup/index.blade.php
  resources/views/team/index.blade.php
  routes/api.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#169 revert
  app/Http/Controllers/HomeController.php
  composer.lock
  public/assets/css/login.css
  public/assets/css/signup.css
  resources/views/home/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/login/index.blade.php
  resources/views/signup/index.blade.php
  routes/api.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#171 Dev
  app/Http/Controllers/TeamController.php
  resources/views/team/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#172 update show team in home
  app/Http/Controllers/HomeController.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#174 updated home page
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#175 created certificate template resource and migration
  app/Filament/Resources/CertificateTemplateResource.php
  app/Filament/Resources/CertificateTemplateResource/Pages/CreateCertificateTemplate.php
  app/Filament/Resources/CertificateTemplateResource/Pages/EditCertificateTemplate.php
  app/Filament/Resources/CertificateTemplateResource/Pages/ListCertificateTemplates.php
  database/migrations/2024_10_08_021913_create_certificate_templates_table.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#176 updates
  app/Filament/Resources/CertificateTemplateResource.php
  app/Filament/Resources/CertificateTemplateResource/Pages/CreateCertificateTemplate.php
  app/Filament/Resources/CertificateTemplateResource/Pages/EditCertificateTemplate.php
  app/Filament/Resources/CertificateTemplateResource/Pages/ListCertificateTemplates.php
  database/migrations/2024_10_08_021913_create_certificate_templates_table.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#177 update Mail message in event and user notification
  app/Notifications/EventNotification.php
  app/Notifications/UserNotification.php
Labels: hacktoberfest, hacktoberfest-accepted

#178 Dev
  app/Filament/Resources/RoleResource.php
  database/migrations/2024_09_30_043055_create_roles_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/home/index.blade.php
  resources/views/team/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#179 fix: events page message
  resources/views/events/index.blade.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#180 Login page added
  app/Http/Controllers/HomeController.php
  resources/views/login/index.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#181 updated design of certificate resource
  app/Filament/Resources/CertificateTemplateResource.php
  app/Models/CertificateTemplate.php
  database/migrations/2024_10_08_021913_create_certificate_templates_table.php
Labels: hacktoberfest, hacktoberfest-accepted

#182 signup page added
  app/Http/Controllers/HomeController.php
  resources/views/signup/index.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#183 updated certificate resource list page
  app/Filament/Resources/CertificateTemplateResource.php
Labels: hacktoberfest, hacktoberfest-accepted

#184 features
  app/Filament/Resources/CertificateTemplateResource.php
  app/Http/Controllers/HomeController.php
  app/Models/CertificateTemplate.php
  app/Notifications/EventNotification.php
  app/Notifications/UserNotification.php
  database/migrations/2024_10_08_021913_create_certificate_templates_table.php
  resources/views/login/index.blade.php
  resources/views/signup/index.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#185 Dev
  app/Filament/Resources/EventsResource.php
  app/Filament/Resources/UserResource.php
  composer.json
  composer.lock
Labels: hacktoberfest, hacktoberfest-accepted

#186 Dev
  app/Filament/Resources/CertificateTemplateResource.php
  app/Filament/Resources/DeveloperGroupResource.php
  app/Filament/Resources/GalleryResource.php
  resources/views/home/index.blade.php
  resources/views/layouts/inlcudes/footer.blade.php
  resources/views/login/index.blade.php
  resources/views/signup/index.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#187 updated placeholder
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#189 Dev
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/HomeController.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/home/index.blade.php
  resources/views/layouts/inlcudes/footer.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#190 Added registration
  app/Http/Controllers/AuthController.php
  composer.lock
  database/migrations/2024_09_30_083115_add_foriegns_to_users.php
  database/migrations/2024_09_30_083338_add_foriegn_branch_to_users.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/home/index.blade.php
  resources/views/layouts/inlcudes/footer.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#193 Dev
  app/Filament/Resources/UserResource.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/HomeController.php
  app/Models/User.php
  database/migrations/2024_09_30_083115_add_foriegns_to_users.php
  resources/views/about/index.blade.php
  resources/views/auth/register.blade.php
  resources/views/layouts/inlcudes/nav.blade.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#194 feature: show user's social media links
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/TeamController.php
  resources/views/about/index.blade.php
  resources/views/team/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#196 Dev
  app/Filament/Resources/EventsResource.php
  app/Models/Certificate.php
  app/Models/Events.php
  database/factories/CertificateFactory.php
  database/migrations/2024_09_29_170444_create_events_table.php
  database/migrations/2024_10_23_024007_create_certificates_table.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#198 updated developer groups in home
  app/Filament/Resources/DeveloperGroupResource.php
  app/Http/Controllers/HomeController.php
  resources/views/home/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#199 updated certificatetemplate model and resource
  app/Filament/Resources/CertificateTemplateResource.php
  app/Models/Certificate.php
  composer.lock
  database/migrations/2024_10_08_021913_create_certificate_templates_table.php
  database/migrations/2024_10_23_024007_create_certificates_table.php
  routes/web.php
Labels: hacktoberfest, hacktoberfest-accepted

#200 Multiple fixes
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/HomeController.php
  public/assets/css/events.css
  resources/views/auth/login.blade.php
  resources/views/events/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#201 feature mergr
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/HomeController.php
  public/assets/css/events.css
  resources/views/auth/login.blade.php
  resources/views/events/index.blade.php
Labels: hacktoberfest, hacktoberfest-accepted

#202 Dev
  app/Filament/Resources/CertificateResource.php
  app/Filament/Resources/CertificateResource/Pages/CreateCertificate.php
  app/Filament/Resources/CertificateResource/Pages/EditCertificate.php
  app/Filament/Resources/CertificateResource/Pages/ListCertificates.php
Labels: hacktoberfest, hacktoberfest-accepted

#205 Resize uploaded images to 300x300 pixels before saving to the database
  app/Filament/Resources/GalleryResource.php
  app/Models/gallery.php
  composer.json
  composer.lock
  config/app.php
  database/migrations/2024_10_28_151027_modify_gallery_images_column_in_galleries_table.php
Labels: hacktoberfest, hacktoberfest-accepted

#206 image resize feature
  app/Filament/Resources/GalleryResource.php
  app/Models/gallery.php
  composer.json
  composer.lock
  config/app.php
  database/migrations/2024_10_28_151027_modify_gallery_images_column_in_galleries_table.php
Labels: hacktoberfest, hacktoberfest-accepted

#207 Dev
  app/Http/Controllers/HomeController.php
  app/Models/gallery.php
  composer.json
  composer.lock
  database/factories/UserFactory.php
  database/seeders/DatabaseSeeder.php
Labels: hacktoberfest, hacktoberfest-accepted
